### ISSUE TITLE
Campus Life requirements

### ISSUE THREAD

**Issue by akzhy** [infincek/gatsby-site#15]
What kind of data are needed for campus life page ? Is it a usual page or does it include  anything special items like gallery ?

Comment any features that are to be added to the campus life page.

**Comment by Athul-CA** [comment]
My photo😂😂

**Comment by samanyuneelson** [comment]
NSS page layout needs to have a couple of photos followed by the discription (text). Gallery Page needs to have a photoviewer. Rest of the pages have additional websites and Lumire can have a comin soon redirect. Any other suggesions? @athul  @akzhy

**Comment by samanyuneelson** [comment]
Also me and akhil will pick up on the versioning system you asked abt  @akzhy

**Comment by samanyuneelson** [comment]
Also what abt CEK-Open-Source club deets @athul

**Comment by athul** [comment]
> NSS page layout needs to have a couple of photos followed by the discription (text). Gallery Page needs to have a photoviewer. Rest of the pages have additional websites and Lumire can have a comin soon redirect. Any other suggesions? @athul @akzhy

Why is there a need for Gallery in the First Place?


> Also what abt CEK-Open-Source club deets @athul

Yeah I'll work on it by the end... So much to Copy Paste

**Comment by akzhy** [comment]
It's really hard to create seperate page for each item

**Comment by akzhy** [comment]
Also data adding maybe a bit too hard for gallery pages

**Comment by athul** [comment]
Doesn't `gatsby-node.js` do this stuff? Making a new page with diff data with a template?

**Comment by athul** [comment]
We'll make a blog🤑🤑😂😂

**Comment by akzhy** [comment]
I mean it does but I will have to create a template file for each of those

**Comment by samanyuneelson** [comment]
so should we extent the campus life segment when  clicked on ?

**Comment by samanyuneelson** [comment]
When u mean its hard, Is it hard to make them or that its time consuming.  If time is the problem then I am ready to learn how to make additional pages provide u could show me how. @akzhy

**Comment by akzhy** [comment]
By hard, creating a working gallery requires knowledge of certain of libraries (I have used masonry.js). Then we will have to find a way to feed the image URLs, text data to the  library. So it is time consuming because we will first have to find a react component that can create image grid. And it is hard because we will have to experiment with different methods to find the best way to include images

**Comment by akzhy** [comment]
@samanyuneelson Gallery cannot be a normal markdown file. It probably has to be a json or yaml file depending on the usage. So it might be a little complicated.

**Comment by samanyuneelson** [comment]
> @samanyuneelson Gallery cannot be a normal markdown file. It probably has to be a json or yaml file depending on the usage. So it might be a little complicated.

ok then we can scrap the gallery for now.



> It's really hard to create seperate page for each item

Can I lay my hands on making new pages, editing  navbar contents and adding quick links.

**Comment by akzhy** [comment]
Yeah. Just follow the same structure as other files.

**Comment by samanyuneelson** [comment]
K then give me a day to add some pages to the website. I'll try adding the NSS page, make the quick links and rearrange navbar contents. @akzhy

**Comment by athul** [comment]
@samanyuneelson singlepage.js is the Template

**Comment by samanyuneelson** [comment]
wokay
