### ISSUE TITLE
Gatsby Develop Error 

### ISSUE THREAD

**Issue by samanyuneelson** [infincek/gatsby-site#20]
gatsby develop

success open and validate gatsby-configs - 0.183 s
success load plugins - 4.141 s
success onPreInit - 0.046 s
success initialize cache - 0.058 s
success copy gatsby files - 0.278 s
success onPreBootstrap - 0.070 s
info Creating GraphQL type definition for File
info Creating GraphQL type definition for File
info Creating GraphQL type definition for File
success source and transform nodes - 0.336 s
success building schema - 0.697 s
success createPages - 0.089 s
success createPagesStatefully - 0.092 s
success onPreExtractQueries - 0.058 s
success update schema - 0.072 s
success extract queries from components - 0.561 s
success write out requires - 0.095 s
success write out redirect data - 0.053 s
success onPostBootstrap - 0.044 s
⠀
info bootstrap finished - 70.420 s
⠀
success run static queries - 0.262 s — 9/9 43.62 queries/second
success run page queries - 0.068 s — 5/5 230.71 queries/second
 WARNING  Compiled with 1 warnings                                                            9:57:56 PM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

D:\Infin\Collegewebsite\gatsby-site\src\components\navbar.js
  202:7  warning  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md         jsx-a11y/anchor-is-valid
  226:9  warning  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  228:9  warning  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  230:9  warning  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

✖ 4 problems (0 errors, 4 warnings)

⠀
You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
You can now view cek-website in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀
‼ ｢wdm｣:
i ｢wdm｣: Compiled with warnings.
Error loading a result for the page query in "/404.html". Query was not run and no cached result was found.
Page not found /404.html

———————————————————————————————————————————————————————————————————————————————————————————————————————
—
11 pages                                                                                     cek-websit
e

**Comment by akzhy** [comment]
Type the below command once

```
gatsby clean
``` 

And then

```
gatsby develop
```

**Comment by samanyuneelson** [comment]
I followed as @akzhy  instructed. The error persists. I am going to delete and clone the repo again

**Comment by samanyuneelson** [comment]
solved!
