### ISSUE TITLE
Tables in Markdown

### ISSUE THREAD

**Issue by samanyuneelson** [infincek/gatsby-site#25]
How do I customise my tables in markdown 
![2019-08-20 (1)](https://user-images.githubusercontent.com/22994948/63350013-3e4a6480-c37a-11e9-9fcf-b0d4b4e1fd9c.png)

**Comment by athul** [comment]
http://www.tablesgenerator.com/markdown_tables

**Comment by akzhy** [comment]
Styling or table rows/cols ?

**Comment by samanyuneelson** [comment]
I am using table generator but the generated table looks like above . I need to have some more area for the cells. Rit now they look so small

**Comment by akzhy** [comment]
@samanyuneelson They seem adequate ? Do you mean the height or the width of the cells ?

**Comment by samanyuneelson** [comment]
@akzhy  both the height and width

**Comment by samanyuneelson** [comment]
> @samanyuneelson They seem adequate ? Do you mean the height or the width of the cells ?

is this a preset design in CSS

**Comment by athul** [comment]
Tables in Markdown are dynamic.They change by the existence of Data

**Comment by akzhy** [comment]
Wait I edited your comment instead of replying

**Comment by akzhy** [comment]
I can do that ? 🤨

**Comment by samanyuneelson** [comment]
![2019-08-20 (3)](https://user-images.githubusercontent.com/22994948/63355637-0ea05a00-c384-11e9-811b-060cccbb2cf5.png)
it looks like this now

**Comment by akzhy** [comment]
It needs a bit of padding for the header, and perhaps a color change. Otherwise it looks good.

**Comment by akzhy** [comment]
@samanyuneelson .

**Comment by samanyuneelson** [comment]
> It needs a bit of padding for the header, and perhaps a color change. Otherwise it looks good.

what can we do abt the size of both the tables being different. @akzhy

**Comment by akzhy** [comment]
@samanyuneelson we can make them both full width. Also which template are you using ?

**Comment by samanyuneelson** [comment]
@akzhy  singlepage

**Comment by samanyuneelson** [comment]
![2019-08-20 (4)](https://user-images.githubusercontent.com/22994948/63359257-0d722b80-c38a-11e9-9265-7af2d32e03cf.png)
chik chik

**Comment by akzhy** [comment]
Okay great
