### ISSUE TITLE
creating task cards

### ISSUE THREAD

**Issue by samanyuneelson** [infincek/gatsby-site#26]
I have started to make a task list to track our progress. An suggesions :)

**Comment by samanyuneelson** [comment]
ill keep this issue open till noon tmrw

**Comment by samanyuneelson** [comment]
https://github.com/orgs/infincek/projects/3

**Comment by akzhy** [comment]
Front page photo slider is already added ?

**Comment by samanyuneelson** [comment]
oops my bad. anything else.

**Comment by samanyuneelson** [comment]
> Front page photo slider is already added ?

Oh i meant that it doesn't move automatically.

**Comment by akzhy** [comment]
Okay. I've added one

**Comment by samanyuneelson** [comment]
the aspect ratio is same for all the campus life photo. The problem still persists ?

**Comment by samanyuneelson** [comment]
> the aspect ratio is same for all the campus life photo. The problem still persists ?

oh wail i'll push the changes
