### ISSUE TITLE
department faculty tiles bug

### ISSUE THREAD

**Issue by samanyuneelson** [infincek/gatsby-site#39]

**Comment by samanyuneelson** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/22994948/64543195-63f7d780-d342-11e9-8f36-104600fd0383.png)

**Comment by samanyuneelson** [comment]
should't there be 3 tiles per row for the faculty section @akzhy

**Comment by akzhy** [comment]
Fixed #40

**Comment by athul** [comment]
I have a suggestion.
> Why not a show source button/link at the bottom

**Comment by samanyuneelson** [comment]
@athul  did't get u? source button at bottom of what?
