### ISSUE TITLE
Readme.md 

### ISSUE THREAD

**Issue by akzhy** [infincek/gatsby-site#4]
Someone create a meaningful `readme.md`, I am too lazy.

**Comment by Athul-CA** [comment]
Will do that akzhy, but we have to wait(probably me), my system is dead and exam shits mate...

**Comment by akzhy** [comment]
Okay.

**Comment by Athul-CA** [comment]
Basically #2 was made to address the same

**Comment by akzhy** [comment]
Well I guess its upto you!!
