### ISSUE TITLE
HTML Files

### ISSUE THREAD

**Issue by athul** [infincek/gatsby-site#48]
Why are there HTML files in this Repository. The Build files are never stored here. 
I found some Files in [here](https://github.com/infincek/gatsby-site/tree/master/data/faculties/rinson-varghese). And its Only in this specific folder

**Comment by athul** [comment]
@akzhy ?

**Comment by athul** [comment]
@samanyuneelson this too

**Comment by samanyuneelson** [comment]
Lets take a look at it tomorrow

**Comment by akzhy** [comment]
Delete all HTML files

**Comment by akzhy** [comment]
Javascript now at 73%
