### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by akzhy** [infincek/gatsby-site#8]
How about creating a versioning system like

`w.x.y.z` 

where `w` denotes the primary version, `x` - secondary, `y` - bug fixes, patches and `z` for data.
This way we can identify when data is added.

Opinions ?

**Comment by Athul-CA** [comment]
Wow That will be awesome?Like for Commit messages or releases?

**Comment by akzhy** [comment]
Mostly commits so that we can differentiate between code and data adding.

**Comment by Athul-CA** [comment]
Yes.... I'd love to work like this :heart_eyes: and I think there is a plugin for SEO optimisation

**Comment by Athul-CA** [comment]
I think I'll disable the bot for a while

**Comment by akzhy** [comment]
I think it is easier to add SEO manually. Will look into it tomorrow.
