### ISSUE TITLE
Its live Nigguhs

### ISSUE THREAD

**Issue by samanyuneelson** [infincek/gatsby-site#83]
Our website is currently live under ce-kgr.org ..... Fast @akzhy

**Comment by athul** [comment]
We lost the old.ce-kgr.org subddomain and found a typo. Maybe Ill Fix that typo. But we need to discuss the stuff for website's subdomains and stuff

**Comment by samanyuneelson** [comment]
> We lost the old.ce-kgr.org subddomain and found a typo. Maybe Ill Fix that typo. But we need to discuss the stuff for website's subdomains and stuff

any updates on  this

**Comment by samanyuneelson** [comment]
![image](https://user-images.githubusercontent.com/22994948/65886593-42769280-e3ba-11e9-9743-f274a6969268.png)

above RIT and first engineering college in list

**Comment by samanyuneelson** [comment]
![image](https://user-images.githubusercontent.com/22994948/65886998-f1b36980-e3ba-11e9-968d-81940dfc45d2.png)

**Comment by samanyuneelson** [comment]
![image](https://user-images.githubusercontent.com/22994948/65887193-2aebd980-e3bb-11e9-9d67-ed05c5aaeb31.png)
👏  @akzhy

**Comment by athul** [comment]
@dhanyajamol was absent today,so couldn't do anything specific
